### ISSUE TITLE
How can I get two or more property?

### ISSUE THREAD

**Issue by Yuricoden** [hmschreiner/node-hubspot-api#10]
![image](https://user-images.githubusercontent.com/19597527/27181775-b1d69228-51e1-11e7-835a-71e479405c8e.png)

![image](https://user-images.githubusercontent.com/19597527/27181768-aa89b446-51e1-11e7-8840-b66aca992774.png)
Why can not I get two or more property?
And how can I get the property not by id. How to get property by email?

**Comment by hmschreiner** [comment]
Hi @Yuricoden,

There's an issue with the method that pass the parameters to the request that's just send the last *property* param to the API. I'm working to fix it on #9.

A method to get a contact by email was not implemented yet, but it's good to know tough. I will work on that as well.

**Comment by hmschreiner** [comment]
Hey @Yuricoden,

I just released version [1.3.0](https://github.com/hmschreiner/node-hubspot-api/releases/tag/v1.3.0) that fixes the problem with getting two or more properties and the method `getContactByEmail` to get a contact by it's email address.

Thank you for your request and support.

**Comment by Yuricoden** [comment]
Always happy to help! =)
