### ISSUE TITLE
Create contact is not a function

### ISSUE THREAD

**Issue by Yuricoden** [hmschreiner/node-hubspot-api#3]
I'm trying to use api to create a contact.
At me why that an error.
Get query working.
Post request does not work
![image](https://cloud.githubusercontent.com/assets/19597527/26503646/3993aeaa-424a-11e7-80f1-8cd9114b7063.png)
![image](https://cloud.githubusercontent.com/assets/19597527/26503663/534df9ea-424a-11e7-8ab4-9da73b61b081.png)

**Comment by hmschreiner** [comment]
Hi @Yuricoden,

Can you please tell me what release you're current using? Also, can you show the part of code where the `api` variable is created? I checked the code and should be working fine.

**Comment by Yuricoden** [comment]
yep 
![image](https://cloud.githubusercontent.com/assets/19597527/26508019/a8edf15a-425b-11e7-99aa-8e7a0e3cc7be.png)

**Comment by hmschreiner** [comment]
What version are you currently using?

**Comment by Yuricoden** [comment]
0.2.1

**Comment by hmschreiner** [comment]
So sorry. I found the error. I forgot to commit the build folder with all updated methods. Please, update to release **v0.2.2** and the problem should be fix. Thank you for your feedback!

**Comment by Yuricoden** [comment]
always happy to help) 
How can I update a property in a hubspot?

![image](https://cloud.githubusercontent.com/assets/19597527/26514193/00926c02-4279-11e7-9746-bb219196cf1d.png)

https://developers.hubspot.com/docs/methods/contacts/v2/update_contact_property

**Comment by hmschreiner** [comment]
Hi @Yuricoden,

The method to update a contact was not implemented yet.

**Comment by Yuricoden** [comment]
It is very interesting to see the implementation.
I think using this package will increase.

**Comment by hmschreiner** [comment]
@Yuricoden this is the next method to be implemented. You can follow the implementation by this issue #4.
