### ISSUE TITLE
How to make an upgrade property?

### ISSUE THREAD

**Issue by Yuricoden** [hmschreiner/node-hubspot-api#7]
![image](https://cloud.githubusercontent.com/assets/19597527/26528349/9684cec8-43b2-11e7-9990-6d31aa1f42e3.png)
For text the post api  works.
![image](https://cloud.githubusercontent.com/assets/19597527/26528395/d20ed1b8-43b3-11e7-80bd-4bd3bff0a790.png)
![image](https://cloud.githubusercontent.com/assets/19597527/26528399/fbf34ff4-43b3-11e7-8ae6-2d1cea3ee025.png)
![image](https://cloud.githubusercontent.com/assets/19597527/26528369/f4ccd7a0-43b2-11e7-9096-07f67ee1c538.png)
And how to make a post for enumeration?
Just choose the right option.
https://developers.hubspot.com/docs/methods/contacts/v2/

**Comment by hmschreiner** [comment]
Hi @Yuricoden, did you try to pass the value of the field? Like:

```javascript
{
  ...
  qualified: 'Qualified',
  ...
}
```

**Comment by Yuricoden** [comment]
Yep its work! Danke =)
