### ISSUE TITLE
How can I return the radio button selected?

### ISSUE THREAD

**Issue by Yuricoden** [hmschreiner/node-hubspot-api#8]
![image](https://user-images.githubusercontent.com/19597527/27004833-51f97684-4e19-11e7-987a-fac0e488e390.png)
![image](https://user-images.githubusercontent.com/19597527/27004843-a5a18466-4e19-11e7-8806-f0f22467bcd2.png)
If I write the text all right, I need to return the data from the frontend
![image](https://user-images.githubusercontent.com/19597527/27004850-db5bf8b6-4e19-11e7-887e-3ab6d736c58f.png)
![image](https://user-images.githubusercontent.com/19597527/27004856-ed3a7a6c-4e19-11e7-8294-9ea7b8faf2dd.png)
![image](https://user-images.githubusercontent.com/19597527/27004858-0850c5d6-4e1a-11e7-8b52-6049d0d3b45a.png)
![image](https://user-images.githubusercontent.com/19597527/27004867-47eb10de-4e1a-11e7-9140-6de551b58bba.png)

**Comment by hmschreiner** [comment]
Hi @Yuricoden,
We need to pass the exactly internal value of the property you're trying to update. Check the settings for this field to see it's internal values for options.

**Comment by hmschreiner** [comment]
Hi @Yuricoden,

Were you able to solve this issue? Can I close it?

**Comment by Yuricoden** [comment]
yep
